model_list:
  - model_name: claude-sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      region_name: us-west-2

general_settings:
    public_routes:
      - "/health*" # All health check routes 
